name: Create Repository Workflow

on:
  repository_dispatch:
    types: [create_repository]

jobs:
  create_repo_job:
    runs-on: ubuntu-latest
    container:
      image: node:17
      options: --entrypoint /bin/bash

    steps:
      - name: Install PNPM
        run: npm install -g pnpm@7.14.2

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "export GH_PAT_SECRET=${{ secrets.GH_PAT }}" >> $GITHUB_ENV

      - name: Set up Git configuration
        run: |
         git config user.email "liaqatsaeed007@gmail.com"
         git config user.name "Liaqat Saeed"

      - name: Execute script to create repository
        run: |
          ./test.sh '${{ toJson(github.event.client_payload) }}'
